[tool.black]
line-length = 88

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "B"]
# Specify the rule codes that Ruff is allowed to fix.
fixable = ["ALL"]  # Allows autofix for all enabled rules.
unfixable = []     # No rules are marked as unfixable.

[tool.pyright]
include = ["banana"]
exclude = ["**/node_modules", "**/__pycache__"]
strict = ["banana"]
pythonVersion = "3.13"
typeCheckingMode = "strict"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-s -vv --cov=banana --cov-report=term"

[tool.poe.tasks]
format = "black ."
lint = "ruff check --fix ."
typecheck = "pyright"
test = "pytest"
all = ["format", "lint", "typecheck", "test"]
